import { describe, it, expect, afterEach, vi } from 'vitest';
import {
    migrateSettings,
    applyTheme,
    applyUIScale,
    systemTheme,
    defaultProvider,
} from '../settingsSlice';
import type { AppSettings } from '../../../types';

// ─────────────────────────────────────────────────────────────────────────────
// CHARACTERIZATION NET for Refactor 19-06 Plan 03 — settingsSlice helper split.
//
// These tests pin the OBSERVABLE behavior of the pure/DOM helpers that are about
// to be extracted from settingsSlice.ts into a co-located settingsHelpers.ts.
// They import from '../settingsSlice' (the stable public path) on purpose: after
// the extraction, settingsSlice.ts must RE-EXPORT the moved symbols, so this file
// MUST pass unchanged both before and after the move. If GLM's extraction changes
// any behavior, one of these fails. DO NOT edit this file during the extraction.
// ─────────────────────────────────────────────────────────────────────────────

describe('migrateSettings — input-shape coverage', () => {
    it('Shape 1: already two-tier (providers[] + presets w/ *AIProviderId) passes through', () => {
        const out = migrateSettings({
            settings: {
                providers: [{ id: 'p1', label: 'X', endpoint: 'http://x', modelName: 'm', apiKey: 'k', apiFormat: 'openai' }],
                presets: [{ id: 'pr1', name: 'N', storyAIProviderId: 'p1', summarizerAIProviderId: 'p1' }],
                activePresetId: 'pr1',
                contextLimit: 8192,
            },
        });
        expect(out.providers).toHaveLength(1);
        expect(out.providers[0].id).toBe('p1');
        expect(out.presets[0].storyAIProviderId).toBe('p1');
        expect(out.activePresetId).toBe('pr1');
        expect(out.contextLimit).toBe(8192);
    });

    it('Shape 2: legacy inline-config presets extract to providers[] and strip inline configs', () => {
        const out = migrateSettings({
            settings: {
                presets: [{ id: 'a', name: 'A', storyAI: { endpoint: 'http://inl', modelName: 'mm', apiKey: 'kk' } }],
            },
        });
        expect(out.providers.length).toBeGreaterThanOrEqual(1);
        const story = out.providers.find(p => p.endpoint === 'http://inl');
        expect(story).toBeDefined();
        expect(out.presets[0].storyAIProviderId).toBe(story!.id);
        // legacy inline config must be gone from the preset
        expect((out.presets[0] as Record<string, unknown>).storyAI).toBeUndefined();
    });

    it('Shape 3: pre-preset legacy (root endpoint/apiKey/modelName) synthesizes one provider + preset', () => {
        const out = migrateSettings({ endpoint: 'http://leg', apiKey: 'kk', modelName: 'mm' });
        expect(out.providers).toHaveLength(1);
        expect(out.providers[0].endpoint).toBe('http://leg');
        expect(out.providers[0].modelName).toBe('mm');
        expect(out.providers[0].apiKey).toBe('kk');
        expect(out.presets).toHaveLength(1);
        expect(out.presets[0].name).toBe('Default Preset');
        expect(out.presets[0].storyAIProviderId).toBe(out.providers[0].id);
    });

    it('empty input falls back to exactly one provider + one preset with safe field defaults', () => {
        const out = migrateSettings({});
        expect(out.providers).toHaveLength(1);
        expect(out.presets).toHaveLength(1);
        expect(out.activePresetId).toBe(out.presets[0].id);
        // field defaults
        expect(out.theme).toBe('light');
        expect(out.contextLimit).toBe(4096);
        expect(out.retrievalAlgorithm).toBe('idf-rrf');
        expect(out.archiveRecallDepth).toBe('standard');
        expect(out.responseLength).toBe('flexible');
        expect(out.uiScale).toBe(1.0);
        expect(out.matureMode).toBe(false);
    });

    it('keeps a valid responseLength and resets an unknown one to flexible', () => {
        expect(migrateSettings({ responseLength: 'short' }).responseLength).toBe('short');
        expect(migrateSettings({ responseLength: 'epic' }).responseLength).toBe('flexible');
    });

    it('dedupes providers with identical endpoint|model|key|format across presets', () => {
        const cfg = { endpoint: 'http://same', modelName: 'm', apiKey: 'k' };
        const out = migrateSettings({
            settings: {
                presets: [
                    { id: 'a', name: 'A', storyAI: { ...cfg } },
                    { id: 'b', name: 'B', storyAI: { ...cfg } },
                ],
            },
        });
        expect(out.providers).toHaveLength(1);
        expect(out.presets[0].storyAIProviderId).toBe(out.presets[1].storyAIProviderId);
    });

    it('carries legacy image endpoint config into its own provider + imageAIProviderId', () => {
        const out = migrateSettings({
            settings: { imageApiEndpoint: 'http://img', imageApiKey: 'ik', imageApiModel: 'im' },
        });
        const img = out.providers.find(p => p.endpoint === 'http://img');
        expect(img).toBeDefined();
        expect(out.presets[0].imageAIProviderId).toBe(img!.id);
    });

    it('backfills a preset missing storyAIProviderId to the first provider', () => {
        const out = migrateSettings({
            settings: {
                providers: [{ id: 'p1', endpoint: 'http://x', modelName: 'm' }],
                presets: [{ id: 'pr1', name: 'N' }],
            },
        });
        expect(out.presets[0].storyAIProviderId).toBe('p1');
    });

    it('unwraps data.settings when present, else treats data as raw', () => {
        const wrapped = migrateSettings({ settings: { contextLimit: 1234 } });
        expect(wrapped.contextLimit).toBe(1234);
        const bare = migrateSettings({ contextLimit: 4321 } as Record<string, unknown>);
        expect(bare.contextLimit).toBe(4321);
    });
});

describe('applyUIScale — DOM side effects', () => {
    afterEach(() => {
        document.documentElement.style.removeProperty('--ui-scale');
        document.documentElement.style.zoom = '';
    });

    it('sets --ui-scale and zoom when scale != 1', () => {
        applyUIScale(1.25);
        expect(document.documentElement.style.getPropertyValue('--ui-scale')).toBe('1.25');
        expect(document.documentElement.style.zoom).toBe('1.25');
    });

    it('clears zoom when scale == 1', () => {
        applyUIScale(1.5);
        applyUIScale(1);
        expect(document.documentElement.style.getPropertyValue('--ui-scale')).toBe('1');
        expect(document.documentElement.style.zoom).toBe('');
    });
});

describe('applyTheme / systemTheme — DOM + matchMedia', () => {
    const realMatchMedia = window.matchMedia;
    afterEach(() => {
        window.matchMedia = realMatchMedia;
        document.documentElement.removeAttribute('data-theme');
    });

    it('applies explicit light/dark directly to data-theme', () => {
        applyTheme('dark');
        expect(document.documentElement.getAttribute('data-theme')).toBe('dark');
        applyTheme('light');
        expect(document.documentElement.getAttribute('data-theme')).toBe('light');
    });

    it('resolves "system" via matchMedia (dark)', () => {
        window.matchMedia = vi.fn().mockReturnValue({ matches: true, addEventListener: () => {} }) as unknown as typeof window.matchMedia;
        expect(systemTheme()).toBe('dark');
        applyTheme('system');
        expect(document.documentElement.getAttribute('data-theme')).toBe('dark');
    });

    it('resolves "system" via matchMedia (light)', () => {
        window.matchMedia = vi.fn().mockReturnValue({ matches: false, addEventListener: () => {} }) as unknown as typeof window.matchMedia;
        expect(systemTheme()).toBe('light');
    });
});

describe('module exports remain stable through the extraction', () => {
    it('defaultProvider is a usable LLMProvider shape', () => {
        // Pinned so a re-export miss during the split fails loudly here.
        expect(defaultProvider).toMatchObject({ endpoint: expect.any(String), modelName: expect.any(String) });
    });

    it('migrateSettings output is assignable to AppSettings (presets/providers present)', () => {
        const out: AppSettings = migrateSettings({});
        expect(Array.isArray(out.presets)).toBe(true);
        expect(Array.isArray(out.providers)).toBe(true);
    });
});
